#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stages('Build') {
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
        stages('Test') {
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "mvn clean install"
            }
        }
    }
}